### ISSUE TITLE
Issue with catkin_make

### ISSUE THREAD

**Issue by kunpengyao** [yias/allegro-hand-ros-kinetic#2]
One CMake Error was reported the first time I run `catkin_make`. It is caused by the missing `CMakeLists.txt` file in the `allegro_hand_moveit` package.
Also, I noticed that this package does not exit in other allegrohand forked packages.
I resolved the issue by removing the moveit package.

**Comment by yias** [comment]
Yes, the moveit package was an old dependency that has been removed and is no longer required. The moveit package is now removed from the master branch. 

If it compiles now, I will close this issue.

**Comment by kunpengyao** [comment]
Yes thanks! Close the issue plz.😁
