### ISSUE TITLE
Compatibility with hand version

### ISSUE THREAD

**Issue by kunpengyao** [yias/allegro-hand-ros-kinetic#3]
Another issue I have found is that the master branch (for ROS kinetic) works only with the old version of Allegro hand.
For Allegro hand of new version, use the melodic branch instead. The melodic version is also compatible with ROS kinetic.

**Comment by yias** [comment]
Does the melodic version work with both hands?

The issue with the right allegro hand (old allegro hand) might be that the urdf file is not correct. I had corrected it for the left allegro hand but not for the right allegro hand. 

Also, one other difference between the new and the old allegro hands is that the encoder's direction and offsets and the motor directions are embedded in the micro-controller in the new version of the allegro hand. For the old allegro hand, instead, they should be loaded by choosing the corresponding zero file in the launch file. Thus, there should be a condition in the launch file for selected which zero file should be loaded depending on the version of the allegro hand or which hand is been selected (left or right).

Hope it helps.

**Comment by kunpengyao** [comment]
I see. The Melodic also works well for the new hand in ROS Kinetic. No longer an issue for me.👍🏻

**Comment by yias** [comment]
Cool, I'm closing the issue.
